### ISSUE TITLE
Restart command does not reload /etc/init/sidekiq configuration file

### ISSUE THREAD

**Issue by ajsharp** [brainyatom/opsworks-sidekiq#3]
I don't have much experience with upstart, but it seems like the /etc/init/sidekiq-appname.conf file only gets reloaded by running `stop sidekiq-appname` and then `start sidekiq-appname`. The major use case here is when environment variables change. An alternate way to fix this would be to not capture environment variables in the configuration file, and expect them to be present on the deploy machine (via /etc/environment or whatever).

Thanks for this great cookbook! It's by far the easiest to use!

**Comment by atomgiant** [comment]
Hi @ajsharp! Thanks for the complements.  I needed this and all the other cookbooks did way more than I needed so I decided to share it.  Glad you find it useful.

I have not run into the restart not reloading the config issue myself... but I haven't had to change any config or environment variables in a while.  On each deploy I am sending the restart command to the process and it creates a new process id (as seen here: https://github.com/brainyatom/opsworks-sidekiq/blob/master/recipes/deploy.rb#L32). 

I just tracked down the restart upstart docs which confirm restart does not reload env vars:
http://upstart.ubuntu.com/cookbook/#restart

I'd like to keep the restart as it stands for the default path, but I'd be willing to accept a pull request if you want to provide another recipe to explicitly stop / start the sidekiq job.  Perhaps this could be done as just a one-off recipe with custom JSON since it would only be needed occasionally.

**Comment by ajsharp** [comment]
Nice, thanks for finding the relevant part of the upstart docs, much appreciated :) What do you think about having an attribute that would allow you to specify the restart method? The recipe could check this in this sort of way:

```ruby
if deploy['sidekiq']['restart_mode'] == 'stop'
  bash 'restart_sidekiq' do
    notifies :stop, "service["sidekiq-#{application}]"
    notifies :start, "service["sidekiq-#{application}]"
  end
else
    # always restart sidekiq on deploy since we assume the code must need to be reloaded
    bash 'restart_sidekiq' do
      code "echo noop"
      notifies :restart, "service[sidekiq-#{application}]"
    end
end
```

This would be a bit cleaner during deploys than having a separate recipe, because I'd still want to use the `sidekiq::deploy` recipe, but adding another one with the hard restart functionality to the run list would effectively bounce the sidekiq process twice on a deploy.

I'm happy to fork and this functionality there, and you can decide if you want to pull it in. Thanks!

**Comment by atomgiant** [comment]
I think that seems like a good approach.  I would accept that pull request.  Could you also add that to the README? :)  Thanks!

**Comment by atomgiant** [comment]
@ajsharp - I decided to just change the restart behavior to start / stop based on another request which included a Pull Request. This is now merged into master.
